package com.ahn.pojo;

import java.util.Date;

public class Kuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kuser.id
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kuser.username
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kuser.birthday
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kuser.sex
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kuser.address
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public Kuser(Integer id, String username, Date birthday, String sex, String address) {
        this.id = id;
        this.username = username;
        this.birthday = birthday;
        this.sex = sex;
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public Kuser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kuser.id
     *
     * @return the value of kuser.id
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kuser.id
     *
     * @param id the value for kuser.id
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kuser.username
     *
     * @return the value of kuser.username
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kuser.username
     *
     * @param username the value for kuser.username
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kuser.birthday
     *
     * @return the value of kuser.birthday
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kuser.birthday
     *
     * @param birthday the value for kuser.birthday
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kuser.sex
     *
     * @return the value of kuser.sex
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kuser.sex
     *
     * @param sex the value for kuser.sex
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kuser.address
     *
     * @return the value of kuser.address
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kuser.address
     *
     * @param address the value for kuser.address
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    @Override
    public String toString() {
        return "Kuser{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", birthday=" + birthday +
                ", sex='" + sex + '\'' +
                ", address='" + address + '\'' +
                '}';
    }
}