package com.ahn.pojo;

import java.util.Date;

public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.pid
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.pname
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.pdate
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private Date pdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.cid
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    private String cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public Products(Integer pid, String pname, Double price, Date pdate, String cid) {
        this.pid = pid;
        this.pname = pname;
        this.price = price;
        this.pdate = pdate;
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public Products() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.pid
     *
     * @return the value of products.pid
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.pid
     *
     * @param pid the value for products.pid
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.pname
     *
     * @return the value of products.pname
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.pname
     *
     * @param pname the value for products.pname
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.price
     *
     * @return the value of products.price
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.price
     *
     * @param price the value for products.price
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.pdate
     *
     * @return the value of products.pdate
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public Date getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.pdate
     *
     * @param pdate the value for products.pdate
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.cid
     *
     * @return the value of products.cid
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.cid
     *
     * @param cid the value for products.cid
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }
}