package com.ahn.dao;

import com.ahn.pojo.Kuser;
import com.ahn.pojo.KuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    long countByExample(KuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    int deleteByExample(KuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    int insert(Kuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    int insertSelective(Kuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    List<Kuser> selectByExample(KuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    Kuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") Kuser record, @Param("example") KuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    int updateByExample(@Param("record") Kuser record, @Param("example") KuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    int updateByPrimaryKeySelective(Kuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kuser
     *
     * @mbg.generated Wed Aug 26 09:43:59 CST 2020
     */
    int updateByPrimaryKey(Kuser record);
}